# Generated by Django 5.1.15 on 2026-03-28 23:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_name", models.CharField(max_length=255)),
                ("storage_key", models.CharField(max_length=500, unique=True)),
                ("mime_type", models.CharField(max_length=100)),
                ("file_size", models.BigIntegerField()),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
