# Generated by Django 5.1.15 on 2026-03-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="hidden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="moderation_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(default="other", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
